services:
  db:
    image: postgres:17.4
    restart: always
    volumes:
      - ./data/index:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:${DB_PORT}
    env_file:
      - .env
  app:
    build:
      context: .
      target: prod
      dockerfile: Dockerfile
    command: node index.js
    ports:
      - ${PORT}:${PORT}
    env_file:
      - .env
    depends_on:
      - db
