services:
  app:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    command: ./start.sh
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/app/src
      - /app/node_modules
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:17.4
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./data/index:/var/lib/postgresql/data
    env_file:
      - .env.dev
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
