services:
  db:
    image: postgres:17.4
    restart: always
    volumes:
      - ./data/index:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: pnpm dev
    ports:
      - ${PORT}:5000
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - db
