services:
  db:
    image: postgres
    restart: always
    volumes:
      - ./data/index:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env
  app:
    build:
      context: .
      target: runner
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
