services:
  app:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    command: ./start.sh
    ports:
      - ${PORT}:${PORT}
    volumes:
      - ./src:/app/src
      - /app/node_modules
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:17.4
    restart: always
    volumes:
      - ./data/index:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env.dev
