# fly.toml app configuration file generated for sh-app-nightly-autumn-dust-6739 on 2025-04-01T00:38:00+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sh-app-nightly-autumn-dust-6739'
primary_region = 'lhr'

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = [ 'app' ]

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
