# fly.toml app configuration file generated for sound-harbor-server-lively-pine-8877 on 2025-03-30T02:25:24+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sh-hono'
primary_region = 'lhr'

[build]
build-target = 'prod'

[env]
NODE_ENV = 'production'

[http_service]
internal_port = 3000
auto_stop_machines = 'stop'
auto_start_machines = true
min_machines_running = 0
processes = [ 'app' ]

[[vm]]
memory = '512mb'
cpu_kind = 'shared'
cpus = 1
